version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3333:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - PGDATABASE=postgres
      - PGHOST=db

  db:
    build:
      context: ./db
    volumes:
      - matt-todo-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  matt-todo-volume:
